{
 "title": "MavSeal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sign ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(vault_sign_request_error_total[20s])",
     "legendFormat": "{{vault}} errors"
    },
    {
     "expr": "increase(signing_ops_total[20s])",
     "legendFormat": "{{vault}}"
    }
   ]
  },
  {
   "title": "Total Ops signed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (op, kind)(signing_ops_total)"
    },
    {}
   ]
  },
  {
   "title": "Vault Latency Over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(vault_sign_request_duration_microseconds[20s])",
     "legendFormat": "{{vault}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Total Ops signed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "sum by (op)(signing_ops_total)", "legendFormat": "{{op}}" },
    {}
   ]
  },
  {
   "title": "Vault Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "vault_sign_request_duration_microseconds",
     "legendFormat": "{{vault}} {{quantile}}"
    }
   ]
  },
  {
   "title": "Total Generic ops signed",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (kind)(signing_ops_total{op=\"generic\"}) ",
     "legendFormat": "{{kind}}"
    },
    {}
   ]
  }
 ]
}